# hyprlock.conf
# Pantalla de bloqueo Cybersigilism

general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    # Fondo por defecto (wallust puede integrarse dinámicamente si se configura)
    path = ~/Imágenes/Wallpapers/fallen_angel.png
    
    # Blur y ajustes estéticos Cybersigilism
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    
    # Colores base Cybersigilism
    outer_color = rgba(203, 166, 247, 1.0) # cba6f7 (Morado Neón)
    inner_color = rgba(17, 17, 27, 0.8)    # 11111b (Fondo Oscuro con transparencia)
    font_color = rgba(205, 214, 244, 1.0)  # cdd6f4 (Texto)
    check_color = rgba(245, 194, 231, 1.0) # f5c2e7 (Rosa - Verificando)
    fail_color = rgba(243, 139, 168, 1.0)  # f38ba8 (Rojo - Fallo)
    
    fade_on_empty = true
    placeholder_text = <i>Contraseña...</i>
    hide_input = false
    position = 0, -120
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(203, 166, 247, 1.0) # cba6f7 (Morado)
    font_size = 90
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 80
    halign = center
    valign = center
}
