# hyprland.conf
# Archivo de entrada (Orquestador)

# Incluyendo los archivos modulares
source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/exec.conf
source = ~/.config/hypr/configs/appearance.conf

# Los siguientes módulos se incluirán a medida que los vayamos creando
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/animations.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/rules.conf

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}
