# ----------------------------------------------------- 
# Configuración de Teclado, Mouse y Touchpad
# ----------------------------------------------------- 
input {
    # Teclado estrictamente en formato Latinoamericano
    kb_layout = latam
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    # Comportamiento del ratón
    follow_mouse = 1       # El foco sigue al cursor
    sensitivity = 0        # 0 es la sensibilidad estándar (sin modificaciones)

    # Configuración del touchpad para la laptop
    touchpad {
        natural_scroll = true   # Scroll invertido (como en smartphones/mac)
        tap-to-click = true     # Tocar para hacer click
        drag_lock = true        # Facilita arrastrar ventanas sin mantener presionado físicamente
    }
}

# Gestos de Touchpad para navegación rápida (Sintaxis para Hyprland v0.51+)
gesture = 3, horizontal, workspace
