# monitors.conf
# Configuración del Monitor

# Forzar resolución 1920x1200 a 144Hz
# Si tu monitor interno tiene un nombre específico (ej. eDP-1),
# puedes reemplazar la primera coma vacía por ese nombre.
monitor = , 1920x1200@144, auto, 1

# Habilitar explícitamente VRR (Variable Refresh Rate / Adaptive Sync)
# para ahorrar batería en imágenes estáticas y mejorar fluidez en juegos.
misc {
    vrr = 0
}
